config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update,:new] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      post 'toggle_follow', to: 'users#toggle_follow'
      get 'followings', to: 'users#followings'
      get 'followers', to: 'users#followers'
    end
  end
  resources :users, only: [:index,:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book = @book_comment.book
    @book_comment.destroy
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<div>
  <% book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %>
      <%= book_comment.user.name %>
      <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
    <% end %>
    </p>
  <% end %>
</div>
<div>
    <%= form_with model: book_comment, url: book_book_comments_path(book), local: false do |f| %>
      <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
      <p><%= f.submit "送信" %></p>
    <% end %>
</div>

app/views/book_comments/_count.html.erb
コメント件数: <%= book.book_comments.count %>

app/views/book_comments/create.js.erb
$('#book_comments').html(' <%= j(render 'book_comments/comment',book: @book, book_comment: @book_comment) %>');
$('#comments_count').html(' <%= j(render 'book_comments/count',book: @book) %>');

app/views/book_comments/destroy.js.erb
$('#book_comments').html(' <%= j render 'book_comments/comment',book: @book, book_comment: @book_comment %>');
$('#comments_count').html(' <%= j(render 'book_comments/count',book: @book) %>');